language: go
go:
- 1.x
- tip
before_install:
  - go install github.com/mattn/goveralls@latest
install:
- bash .travis.sh
- go get -t ./...
- go get golang.org/x/tools/cmd/cover
matrix:
  allow_failures:
  - go: tip
script:
- go test -race -v -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci